version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Set up Python environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            playwright install
            playwright install-deps

      - run:
          name: Set PYTHONPATH
          command: |
            echo "export PYTHONPATH=$PYTHONPATH:$(pwd)" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Run tests and generate HTML report
          command: |
            . venv/bin/activate
            pytest --html=report.html

      - store_artifacts:
          path: report.html
          destination: test-report

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
